#!/usr/bin/env php
<?php

define('FIREUP_START', microtime(true));

require __DIR__.'/vendor/autoload.php';

use FireUp\Console\Console;
use FireUp\Application;

$app = new Application();
$console = new Console($app);
$console->run($argv);